---

- name: Check if cargo is installed
  stat:
    path: $CARGO_HOME
  register: cargo

- name: Install cargo
  when: not cargo.stat.exists
  become: yes
  become_user: "{{ user }}"
  block:
    - name: Download Installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: Install rust/cargo
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust
